Default: &defaults
  database: panda.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: panda_test.sqlite3
  <<: *defaults

Staging:
  database: panda_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: panda_production.sqlite3
  poolsize: 100
  <<: *defaults
